const tagsArray = [
    { id: 1, name: "Illustrator", category_id: 1 },
    { id: 2, name: "After Effects", category_id: 1 },
    { id: 3, name: "Figma", category_id: 1 },
    { id: 4, name: "InDesign", category_id: 1 },
    { id: 5, name: "Photoshop", category_id: 1 },
    { id: 6, name: "DaVinci Resolve", category_id: 1 },
    { id: 7, name: "Sketch", category_id: 1 },
    { id: 8, name: "Adobe XD", category_id: 1 },
    { id: 9, name: "CorelDRAW", category_id: 1 },
    { id: 10, name: "Affinity Designer", category_id: 1 },
    { id: 11, name: "Canva", category_id: 1 },
    { id: 12, name: "GIMP", category_id: 1 },
    { id: 13, name: "Inkscape", category_id: 1 },
    { id: 14, name: "Procreate", category_id: 1 },
    { id: 15, name: "Adobe Premiere Pro", category_id: 1 },
    { id: 16, name: "Final Cut Pro", category_id: 1 },
    { id: 17, name: "Adobe Lightroom", category_id: 1 },
    { id: 18, name: "Cinema 4D", category_id: 1 },
    { id: 19, name: "Blender", category_id: 1 },
    { id: 20, name: "Autodesk SketchBook", category_id: 1 },
    { id: 21, name: "HTML", category_id: 2 },
    { id: 22, name: "CSS", category_id: 2 },
    { id: 23, name: "JavaScript", category_id: 2 },
    { id: 24, name: "Laravel", category_id: 2 },
    { id: 25, name: "React", category_id: 2 },
    { id: 26, name: "WordPress", category_id: 2 },
    { id: 27, name: "Tailwind CSS", category_id: 2 },
    { id: 28, name: "TypeScript", category_id: 2 },
    { id: 29, name: "SQL", category_id: 2 },
    { id: 30, name: "Node.js", category_id: 2 },
    { id: 31, name: "Express.js", category_id: 2 },
    { id: 32, name: "Angular", category_id: 2 },
    { id: 33, name: "Vue.js", category_id: 2 },
    { id: 34, name: "Django", category_id: 2 },
    { id: 35, name: "Flask", category_id: 2 },
    { id: 36, name: "Bootstrap", category_id: 2 },
    { id: 37, name: "Sass", category_id: 2 },
    { id: 38, name: "Less", category_id: 2 },
    { id: 39, name: "GraphQL", category_id: 2 },
    { id: 40, name: "RESTful API", category_id: 2 },
    { id: 41, name: "MongoDB", category_id: 2 },
    { id: 42, name: "MySQL", category_id: 2 },
    { id: 43, name: "PostgreSQL", category_id: 2 },
    { id: 44, name: "SQLite", category_id: 2 },
    { id: 45, name: "Redis", category_id: 2 },
    { id: 46, name: "Webpack", category_id: 2 },
    { id: 47, name: "Babel", category_id: 2 },
    { id: 48, name: "Git", category_id: 2 },
    { id: 49, name: "GitHub", category_id: 2 },
    { id: 50, name: "Bitbucket", category_id: 2 },
    { id: 51, name: "Jira", category_id: 2 },
    { id: 52, name: "Trello", category_id: 2 },
    { id: 53, name: "Slack", category_id: 2 },
    { id: 54, name: "Ruby", category_id: 2 },
    { id: 55, name: "Sanity", category_id: 2 },
    { id: 56, name: "Contentfull", category_id: 2 },
    { id: 57, name: "Github", category_id: 3 },
    { id: 58, name: "Visual Studio Code", category_id: 3 },
    { id: 59, name: "Sublime Text", category_id: 3 },
    { id: 60, name: "Atom", category_id: 3 },
    { id: 61, name: "IntelliJ IDEA", category_id: 3 },
    { id: 62, name: "Eclipse", category_id: 3 },
    { id: 63, name: "NetBeans", category_id: 3 },
    { id: 64, name: "Heroku", category_id: 3 },
    { id: 65, name: "AWS", category_id: 3 },
    { id: 66, name: "Google Cloud Platform", category_id: 3 },
    { id: 67, name: "Microsoft Azure", category_id: 3 },
    { id: 68, name: "Docker", category_id: 3 },
    { id: 69, name: "Kubernetes", category_id: 3 },
    { id: 70, name: "Jenkins", category_id: 3 },
    { id: 71, name: "Travis CI", category_id: 3 },
    { id: 72, name: "CircleCI", category_id: 3 },
    { id: 73, name: "Continuous Integration", category_id: 3 },
    { id: 74, name: "Continuous Deployment", category_id: 3 }
];

export default tagsArray;